### ISSUE TITLE
Trying to display events by; 'this week', 'next week', 'beyond' etc

### ISSUE THREAD

**Issue by richardwiggins** [unionco/calendarize#10] opened 2019-02-01 16:30 UTC
I am attempting to list out events grouped by _this week_, _next week_ and _beyond_. I can get this working with a native custom date field like so:

```
{% set thisWeek = day|date_modify('this Sunday')|date('Y-m-d') %}
{% set nextWeek = day|date_modify('next Monday')|date('Y-m-d') %}
{% set followingWeek = day|date_modify('next Monday +7 days')|date('Y-m-d') %}
{% set eventsThisWeek = craft.entries.section('events').dateFrom(['and', '<= ' ~ thisWeek ]) %}
{% set eventsNextWeek = craft.entries.section('events').dateFrom(['and', '>= ' ~ nextWeek, '<=' ~ followingWeek ]) %}
{% set eventsBeyondNextWeek = craft.entries.section('events').dateFrom(['and', '> ' ~ followingWeek ]) %}
```

But as I'm now trying to use the lovely Calendarize the above is no good to me so I've tried variations on to use `dateTime.startDate` instead:

i.e. `{% set eventsThisWeek = craft.entries.section('events').dateFrom(['and', '<= ' ~ thisWeek ]) %}`

This gives me errors of:

> Impossible to invoke a method ("startDate") on a null variable.

I'm obviously not doing something right or maybe it isn't possible?

Any ideas?

**Comment by richardwiggins** [comment] 2019-02-08 09:25
Don't suppose anyone has any ideas on this one?

**Comment by fvaldes33** [comment] 2019-02-08 23:44
@richardwiggins - I am going to take a look over the weekend. I'll comment back on here my findings.

**Comment by fvaldes33** [comment] 2019-02-11 15:24
@richardwiggins - I was able to add a `between` method to the calendarize twig variable. Usage looks something like this:

```twig
{% set startOfMonth = now|date_modify('first day of this month')|date('Y-m-d') %}
{% set endOfMonth = now|date_modify('last day of this month')|date('Y-m-d') %}
{% set occurrences = craft.calendarize.between(startOfMonth, endOfMonth, { section: ['events', 'liveShows'] }) %}
<p>This Month: {{ startOfMonth }} to {{ endOfMonth }}</p>
<ul>
    {% for occurrence in occurrences %}
        <li>{{ occurrence.title }} @ {{ occurrence.next.format('Y-m-d') }}</li>
    {% endfor %}
</ul>
```

Added in [81c365b](https://github.com/unionco/calendarize/commit/81c365b45318ab3636a1342241db0556b0c1c3c7)

Let me know is this works for you. 

Thanks!

**Comment by richardwiggins** [comment] 2019-02-11 17:10
@fvaldes33 Thanks so much for looking into this, really appreciated but I think something is now broken. I have updated the plugin and even without adding your above example I'm an Exception error from line 288:

`throw new \Exception('Cannot use RRULE with non repeating values', 1);`

**Comment by fvaldes33** [comment] 2019-02-11 19:07
@richardwiggins - my mistake on that last commit. The usage of RRULE needs to be conditionally created differently for non repeating instances. Just pushed the patch for that.

Commit: [9cc016a](https://github.com/unionco/calendarize/commit/9cc016aac4e329be3b62d1197baedd3eda41e7f1)

**Comment by richardwiggins** [comment] 2019-02-12 08:27
@fvaldes33 Thanks man, it's working now but I am getting some slightly unexpected results with your example code. It's outputting the start/end dates seemingly correctly; `This Month: 2019-02-01 to 2019-02-28`, but then it's listing all events, not just events within that time period.

I'm now also getting every repeating occurrence which i.e. an event is repeating 3 times a week and now listing everyone which I don't think I want at the moment. Bit confused, sorry.

<img width="914" alt="screenshot 2019-02-12 at 08 21 46" src="https://user-images.githubusercontent.com/940047/52621766-0250b700-2ea0-11e9-81b7-51904fe6150e.png">

**Comment by fvaldes33** [comment] 2019-02-12 15:05
@richardwiggins - I cannot reproduce the events outside of the time period given. Maybe send over a DB so I can reproduce with your data.

In regards to the repeating occurrences, I believe if someone is looking for all occurrences between dates, after a date or in general upcoming, it should display all of them and not just the entry (parent element) itself.

I am open to suggestions on how this should actually work. I have considered adding something like the following:

To get entries only and not all of their occurrences
```twig
{% set entries = craft.calendarize.entries.upcoming({ section: ['events'] }) %}
{% set entries = craft.calendarize.entries.after('date', { section: ['events'] }) %}
{% set entries = craft.calendarize.entries.between('date', 'date', { section: ['events'] }) %}
```

To get all of their occurrences (as it is now) - I think this is useful in terms of generating a calendar or calendar listing.
```twig
{% set entries = craft.calendarize.upcoming({ section: ['events'] }) %}
{% set entries = craft.calendarize.after('date', { section: ['events'] }) %}
{% set entries = craft.calendarize.between('date', 'date', { section: ['events'] }) %}
```

**Comment by richardwiggins** [comment] 2019-02-12 15:45
Thanks, DB attached.

I think both would be really useful. I can see benefits of each in different use cases.

We're still working out how we want to handle the recurring events on the site tbh. There's even some consideration to showing recurring events completely separately in their own listing but still not sure about this. I haven't tried but is it currently possible to create an `if` statement around this? i.e.

```
{% if event.calendarizeHandle.repeats %}
xxxx
{% else %}
xxx
{% endif %}
```

I'm not I actually like the idea of splitting them but I have seen it done on quite a few events based websites.

[craft_culturemk12-02-201915-16.sql.zip](https://github.com/unionco/calendarize/files/2856395/craft_culturemk12-02-201915-16.sql.zip)

**Comment by fvaldes33** [comment] 2019-02-12 16:11
@richardwiggins - ill take a look at the db now. To answer your other question, you should be able to perform the code you posted.

**Comment by fvaldes33** [comment] 2019-02-12 21:00
@richardwiggins - after fixing the RRULE logic there was left over code that was dumping none repeating events in the array of occurrences when it shouldn't have. Fixed now in 1.2.3.

Fixed [724a68c](https://github.com/unionco/calendarize/commit/724a68c88451823b72eb38d04677685e8114fd24)

**Closed by fvaldes33** 2019-02-12 21:00 UTC

**Comment by richardwiggins** [comment] 2019-02-12 21:15
Cool, thanks man. Will check it out tomorrow after my meetings.

**Comment by richardwiggins** [comment] 2019-02-14 16:06
Hi @fvaldes33, on the whole I've got this working much better now but I'm running into what I see is an issue with entries that have dates which span a past date.

Basically, if I have an event which has a date in the past but its end date is sometime in the future it won't display. Am I missing something? Is it already possible?

**Comment by fvaldes33** [comment] 2019-02-15 03:47
@richardwiggins - I will have to look into this. Everything I have read and seen in regards to the RRULE uses a single date and not a date span. 

I will put this on the roadmap.

**Comment by richardwiggins** [comment] 2019-02-15 09:19
@fvaldes33 Thanks. Hope you can see what I mean though.
